version: 2

models:
  - name: flyer_impressions
    description: testing flyer impressions
    tests:
      - test_flyer_impressions_nonnegative
    columns:
      - name: flyer_impressions
        tests:
          - not_null
